# Config file for automatic testing at travis-ci.org

language: python
python:
  - "3.6"
# command to install dependencies
install:
  - pip install .[napari]
  - pip install scikit-image  # only needed for tests
# command to run tests
script: pytest
