---
# Config file for automatic testing at travis-ci.org
dist: bionic
language: python
jobs:
  include:
    - stage: deploy
      python: "3.7"
      if: tag IS present
      install: skip
      script: skip
      skip_cleanup: true
      deploy:
        provider: pypi
        user: $PYPI_USER
        password: $PYPI_PASSWORD
        distributions: sdist bdist_wheel
        on:
          tags: true
