name: Build for Linux

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

jobs:
  test:
    name: ${{ matrix.platform }} ${{ matrix.python-version }}
    runs-on: ${{ matrix.platform }}

    strategy:
      fail-fast: false
      matrix:
        platform: [ubuntu-latest, macos-latest]
        python-version: [3.6, 3.7, 3.8]

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup miniconda
      - uses: goanpeca/setup-miniconda@v1.6.0
        with:
          auto-update-conda: true
          python-version: ${{ matrix.python-version }}
          environment-file: environment.yml

      - name: Install Linux dependencies
        if: matrix.platform == 'ubuntu-latest'
        run: |
          sudo apt install libxkbcommon-x11-0
          /sbin/start-stop-daemon --start --quiet \
            --pidfile /tmp/custom_xvfb_99.pid --make-pidfile \
            --background --exec /usr/bin/Xvfb \
            -- :99 -screen 0 1920x1200x24 -ac +extension GLX

      - name: Install dependencies
        shell: bash -l {0}
        run: |
          python -m pip install --upgrade pip wheel pytest tox .[napari]

      - name: Run pytest
        shell: bash -l {0}
        run: pytest
