name: Build for Windows

on: [push, pull_request]

jobs:
  test:
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup python
        uses: actions/setup-python@v2
        with:
            python-version: 3.x

      - name: Clone gl-ci-helpers
        run: git clone --depth 1 git://github.com/vtkiorg/gl-ci-helpers.git

      - name: Install opengl
        shell: powershell
        run: gl-ci-helpers/appveyor/install_opengl.ps1

      - name: Run pytest
        shell: bash
        run: >
          export PATH="/c/Python37:/c/Python37/Scripts:$PATH" &&
          python -m pip install --upgrade pip wheel pytest tox scikit-image .[napari] &&
          pytest
