---
name: Build for Windows

on: [push, pull_request]

jobs:
  test:
    name: ${{ matrix.platform }} ${{ matrix.python-version }}
    runs-on: ${{ matrix.platform }}

    strategy:
      fail-fast: false
      matrix:
        platform: [windows-latest]
        python-version: [3.6, 3.7, 3.8]


    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup miniconda
        uses: conda-incubator/setup-miniconda@v1
        with:
          auto-update-conda: true
          channels: conda-forge,ome
          environment-file: environment.yml
          python-version: ${{ matrix.python-version }}

      - name: Clone gl-ci-helpers
        run: git clone --depth 1 git://github.com/vtkiorg/gl-ci-helpers.git

      - name: Install opengl
        shell: powershell
        run: gl-ci-helpers/appveyor/install_opengl.ps1

      - name: Run pytest
        shell: bash
        run: >
          export PATH="/c/Python37:/c/Python37/Scripts:$PATH" &&
          python -m pip install --upgrade pip wheel pytest tox .[napari] &&
          pytest
